export const refs = {
  account: document.querySelector('.account__link'),
  signin: document.querySelector('.modal-signin__backdrop'),
  signinClose: document.querySelector('.modal-signin__close-btn'),
  btnRef: document.querySelector('.modal-signin__button'),
  btnToUp: document.querySelector('.button__up'),
  container: document.querySelector('.films .container'),
  watchedBtn: document.querySelector('.header__buttons-library--watched'),
  queueBtn: document.querySelector('.header__buttons-library--queue'),
  spinner: document.querySelector('.js-spinner'),
  filmsList: document.getElementsByClassName('films__list'),
  containerForModal: document.querySelector('.js-container'),
  modal: document.querySelector('[data-modal]'),
  modalVideo: document.querySelector('[data-modal-video]'),
  closeModalBtn: document.querySelector('[data-modal-close]'),
  modalFilmBtnsContainerRef: document.getElementsByClassName(
    'modal-film__wrapper-btn'
  ),
  openModalTeamBtn: document.querySelector('[data-modal-team-open]'),
  modalTeam: document.querySelector('[data-modal-team]'),
  closeModalTeamBtn: document.querySelector('[data-modal-team-close]'),
  arrowPrevRef: document.getElementsByClassName('pagination-prev'),
  arrowNextRef: document.getElementsByClassName('pagination-next'),
  formSearchFilmsRef: document.querySelector('#search-form'),
  paginationRef: document.querySelector('#pagination'),
  themeContainerRef: document.querySelector('.theme-container'),
  themModalRef: document.querySelector('.modal-film'),
  themFooterRef: document.querySelector('.js-them-footer'),
  footerRef: document.querySelector('.footer__content'),
  signInModalRef: document.querySelector('.modal-signin__container'),
  spinnerLoadingTextRef: document.querySelector('.load'),
  spinnerHandsRef: document.querySelector('.hands'),
  spinnerBodyRef: document.querySelector('.body'),
  modalHeaderRef: document.querySelector('.modal-signin__title'),
}
