import './js/main-initial-films';
import './js/search-films';
import './js/modal-film';
import './js/modal-team';
import './js/theme-switcher';
import './js/firebase';
import './js/auth';
import './js/modal-singin';
import './js/button-up';
